### ISSUE TITLE
use of ci functions with vector arguments

### ISSUE THREAD

**Issue by nlpaces** [RajeswaranV/proportion#1]
I don't know if this is a bug.

I have two equal lengthed vectors, x and n. In each row x is always <= n.

I want to get a ci for each row of the two vectors

So ciEXx(x = x, n = n, 0.05, 1) is my function call.

Error in ciEXx(x = x, n = n, 0.05, 1) : 
  'x' has to be a positive integer between 0 and n

Any way of using vector arguments for x and n?

Nathan

**Comment by RajeswaranV** [comment]
As of now we support only scalar values for x and n for ciEXx. The function calculates for x value up to n.
